const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      Image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Slim shirt',
      slug: 'Adidas-slim-shirt',
      category: 'shirts',
      Image: '/images/p2.jpg',
      price: 250,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike fit pant',
      slug: 'Nike-dit-pant',
      category: 'Pants',
      Image: '/images/p3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      name: 'Adidas fit pant',
      slug: 'adidas-dit-pant',
      category: 'Pants',
      Image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
  ],
};

export default data;
